version: 0.0
os: linux
files:
  - source: web
    destination: /var/www/html
  - source: api/target/release/api
    destination: /usr/local/bin
file_exists_behavior: OVERWRITE
permissions:
  - object: /usr/local/bin/api
    mode: 755
hooks:
  BeforeInstall:
    - location: deploy-scripts/clear-web-directory.sh
    - location: deploy-scripts/unlink-api-executable.sh
  ApplicationStart:
    - location: deploy-scripts/restart-api.sh
      timeout: 180
