version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=race_planner
      - POSTGRES_PASSWORD=RacingPlanner!2
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
  api:
    build: .
    environment:
      - UI_ORIGIN=http://localhost:9000
      - DATABASE_URL=postgres://race_planner:RacingPlanner!2@db/race_planner
      - RUST_LOG=debug
    ports:
      - '3000:80'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    depends_on:
      - db
volumes:
  db-data:
