[package]
name = 'endurance_racing_planner_common'
version = '0.1.0'
edition = '2018'
[dependencies.serde]
version = '1.0.136'
features = ['derive']

[dependencies.chrono]
version = '0.4.19'
features = ['serde']

[dependencies.uuid]
version = '1.2.2'
features = [
    'v4',
    'serde',
    'js',
]
