name: Build and Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:    
      OAUTH_CLIENT_ID: 709154627100-di88dffek3d6mrvgnr83kg4jlh28hopm.apps.googleusercontent.com
      API_BASE_BATH: https://enduranceraceplanner.com/api/

    steps:
    - uses: actions/checkout@v3
    - name: Setup environment variables
      run: echo "API_BASE_PATH=$API_BASE_PATH\nOAUTH_CLIENT_ID=$OAUTH_CLIENT_ID" >> .env
    - name: Build rust
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Restore npm
      working-directory: ./web
      run: npm ci
    - name: Build npm
      working-directory: ./web
      run: npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: web
        path: web/dist/**/*.*
        if-no-files-found: error
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: api
        path: "**/target/release/api"
        if-no-files-found: error    

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download API Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        path: ./api
        name: api
    - name: Download Web Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        path: ./web
        name: web
    - name: List the web files
      run: ls -R ./web
    - name: List the api files
      run: ls -R ./api
    
