name: PR Build and Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
      
jobs:
  api-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release -p api
    - name: Run tests
      run: cargo test --verbose -p api
        
  web-build:
    runs-on: ubuntu-latest

    env:      
      OAUTH_CLIENT_ID: fake_client_id
      API_BASE_BATH: fake_api_base_path
      
    steps:
    - uses: actions/checkout@v3    
    - name: Run tests
      run: cargo test --verbose -p web
    - name: Restore
      working-directory: ./web
      run: npm ci
    - name: Build
      working-directory: ./web
      run: npm run build
