name: PR Build and Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
      
jobs:
  build:
    runs-on: ubuntu-latest

    env:      
      OAUTH_CLIENT_ID: fake_client_id
      API_BASE_BATH: fake_api_base_path

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Setup environment variables
      run: echo "API_BASE_PATH=$API_BASE_PATH\nOAUTH_CLIENT_ID=$OAUTH_CLIENT_ID" >> .env
    - name: Build rust
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Restore npm
      working-directory: ./web
      run: npm ci
    - name: Build npm
      working-directory: ./web
      run: npm run build
