name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: race-planner
        path: "**/target/release/**/*.*"
        if-no-files-found: error

  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    environment: production
    runs-on: ubuntu-latest
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: race-planner
    - name: List the artifact files
      run: ls -R
    
