FROM node as base

ENV RUST_VERSION=1.65.0

RUN apt-get -y update && \
    apt-get -y install \
    git \
    gcc \
    tar

RUN curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal --default-toolchain $RUST_VERSION -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

ENTRYPOINT [ "bash", "-c" ]